# Favicon
# ---------------
favicon: https://pic.imgdb.cn/item/62c4ff0d5be16ec74ac035b9.png

# Colors
colors:
  primary: '#f07c82'
  # bg: "#A5DEE4"
  selection_bg: '#D05A6E' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:


# Fonts
font:
  cdn:
    enable: false
    lib:

  serif:
    family: '''Songti SC'', STZhongsong, STKaiti, KaiTi, Georgia, serif'
  sans_serif:
    family: '''éœé¹œæ–‡æ¥·'', å¾®è½¯é›…é»‘, ''PingFang SC'', Arial, sans-serif'
  monospace:
    family: '''Comic Sans MS'', ''Cascade Code PL'', ''Microsoft YaHei'', Monaco, monospace'

# Social Links.
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
#  - name: QQ 1847258390
#    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
#    link: https://qm.qq.com/cgi-bin/qm/qr?k=kZJzggTTCf4SpvEQ8lXWoi5ZjhAx0ILZ&jump_from=webapi
#    icon: icon-qq-line
#    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/weekdaycare
    icon: ri:github-line
    color: "#6e5494"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1387091413
    icon: ri:netease-cloud-music-line
    color: "#C20C0C"
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/355825473
    icon: ri:bilibili-line
    color: "#FF8EB3"
#  - name: E-Mail
#    link: 1847258390@foxmail.com
#    icon: icon-mail-line
#    color: "#8E71C1"

# Extra links
pages:
  - name: æˆ‘çš„äº‘ç›˜
    url: https://weekpan.cf/
    icon: ri:cloud-line
    color: dodgerblue

# Sidebar Avatar
avatar:
  enable: true
  url: https://pic.imgdb.cn/item/630c05de16f2c2beb1d86de2.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: true
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ¤”
    message: æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ



# main menu navigation
menu:
  custom:
    title: ispeak
    path: /ispeak
    icon: bx:message-alt-detail

wordcloud:
  enable: true
  height: 350

# You can set color for every tag or category.
tags:
  ç”Ÿæ´»: "#9ADDB3"
  æ•´æ´»: "#4980C2"
  ä»£ç : "#61dafb"
  ä½œä¸š: "#227D51"
  hexo: "#FACAC0"
  ç™½å«–: "#FF00FF"
  æ•™ç¨‹: "#66CDAA"
  æŠ€æœ¯: "#708090"

categories:
  å…¶ä»–: "#854836"
  å­¦ä¹ : "#F14E32"
  æ£é¼“: "#877F6C"
  éšç¬”: "#7B68EE"

codeblock:
  copy_btn: true

# UI
banner:
  enable: true
  title: æ¶›å£°ä¾æ—§
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line


# custom your color in fireworks
fireworks:
  enable: true
  colors:
    - "249, 204, 226"
    - "242, 156, 177"
    - "245, 212, 217"
    # - '3, 28, 95'
    # - '0, 8, 55'

cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur


bg_image:
  enable: true
  url: https://pic.imgdb.cn/item/630d58fc16f2c2beb1a9679f.jpg # recomend image related to your mode
  dark: https://pic.imgdb.cn/item/630c11b216f2c2beb1ddc531.jpg
  # blur: 20px
  opacity: 0.9

# Reward (Donate)
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: false
  icon: icon-hand-coin-line
  comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/alipay-qrcode.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/qqpay-qrcode.png
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/wechatpay-qrcode.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line
    # - name: paypal
    #   link: https://paypal.com
    #   path: https://www.paypalobjects.com/images/shared/paypal-logo-129x32.svg
    #   color: "#2D70B5"
    #   icon: icon-paypal-line

# Footer Settings
# ---------------
footer:
  since: 2021
  live_time:
    enable: true
    prefix: å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: ãƒ¾(â€¢Ï‰â€¢`)o
    start_time: "2021-11-16T23:30:00"

# third party
# ----------------

# search
algolia_search:
  enable: true
  hits:
    per_page: 10 # the number of search results per page

engine_search:
  enable: false

# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡
medium_zoom: true

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line
  
# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: true
  count: true
  time: false

# ä¸€è¨€
say:
  enable: true
  api: /sentences/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

# å…¬å‘Š
notice:
  enable: false
  content: vercel.appè¢«DNSæ±¡æŸ“äº†ï¼Œæ–°åŸŸå<a href="https://weekdaycare.tk">https://weekdaycare.tk </a>


# Analysis
# ---------------
google_analytics:
  enable: false
  # GA4
  id: G-K8QLLZPTBV
  
# comments
waline:
  enable: true
  serverURL: https://weekcomment.tk/
  # visitor: true
  comment: true
  emoji:
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://fastly.jsdelivr.net/gh/walinejs/emojis@latest/weibo/

# Mermaid å…è®¸æ‚¨ä½¿ç”¨æ–‡æœ¬å’Œä»£ç åˆ›å»ºå›¾è¡¨å’Œå¯è§†åŒ–
mermaid:
  enable: false
  options: # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    startOnload: true # default true
  global: false # default true
  

